version: '3.9'

services:
  db:
    image: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  server:
    build: .
    restart: always
    command: [ "air" ]
    container_name: Belajar
    volumes:
      - .:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
        - .env  
    depends_on:
      - db

volumes:
  postgres_data: